version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: makova
      MYSQL_USER: makova
      MYSQL_PASSWORD: 9yIqQ5NxFTfCTQT
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
